
# -*- coding: utf-8 -*-
"""fonction_SBB

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Faj9zuhwU99Fj9mnvV_-51B5vMfjKVm9

Classification report function
"""

# import libraries
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score

import seaborn as sns
import pandas as pd

# code to generate and print the classification report goes here

def print_classification_report(true_labels, predicted_labels, digits=5):
  report = classification_report(true_labels, predicted_labels)
  print(report)

# create a function to print confusion matrix
def display_confusion_matrix(y_true, y_pred):
    sns.set_style("whitegrid")
    sns.heatmap(pd.DataFrame(confusion_matrix(y_true, y_pred)), annot=True, cmap='Blues', fmt='.4g')

# create function to print accuracy, recall and f1
def print_classification_metrics(true_labels, predicted_labels):
  report = classification_report(true_labels, predicted_labels, output_dict=True)
  accuracy = report['accuracy']
  recall = report['weighted avg']['recall']
  f1 = report['weighted avg']['f1-score']

  print(f'Accuracy: {accuracy:.4f}')
  print(f'Recall: {recall:.4f}')
  print(f'F1 Score: {f1:.4f}')
